//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Управляющая_компания_ЖКХ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиенты
    {
        public int ID_Client { get; set; }
        public int ID_Services { get; set; }
        public string Address { get; set; }
    
        public virtual Услуги Услуги { get; set; }
    }
}
